let questions = [
    'favourite breakfast food?',
    'favourite pizza topping/s?',
    'favourite fruit?',
    'favourite party song?',
    'favourite hip-hop song',
    'favourite rock song?',
    'guilty pleasure?',
    'favourite party snack?',
    'favourite pop song?',
    'year of birth?',
    'age?',
    'favourite vegetable?',
    'favourite dessert?',
    'favourite food?',
    'favourite cultural cuisine?',
    'favourite cake?',
    'favourite alcoholic drink?',
    'favourite coffee order?',
    'favourite cartoon cat?',
    'favourite movie?',
    'favourite country you\’ve visited?',
    'country you most want to visit?',
    'favourite place to go with family?',
    'favourite vacation you’ve taken?',
    'favourite fictional place you\’d want to visit?',
    'favourite thing about traveling?',
    'favourite dinosaur?',
    'favourite breed of dog?',
    'favourite season?',
    'your favourite flower?',
    'favourite animal?',
    'favourite native animal?',
    'favourite type of bear?',
    'favourite reptile?',
    'your favourite bird?',
    'favourite way to spend a rainy day?',
    'favourite way to spend a sunny day?',
    'favourite sea creature?',
    'favourite small mammal?',
    'favourite big cat?',
    'favourite wild animal?',
    'favourite sport?',
    'favourite childhood memory?',
    'favourite board game?',
    'favourite children’s show?',
    'favourite toy as a child?',
    'opinion of the best age of your life?',
    "favourite Christmas present you've ever received?",
    'favourite superhero?',
    'favourite video game?',
    'favourite quote?',
    'favourite place to shop?',
    'favourite perfume/cologne?',
    'favourite occasion to dress up for?',
    'favourite hairstyle?',
    'favourite outfit you have?',
    'favourite soap scent?',
    'favourite article of clothing?',
    'favourite luxury brand?',
    'favourite candle scent?',
    'favourite extracurricular activity?',
    'favourite day of the week?',
    'favourite holiday?',
    'favourite kind of house?',
    'favourite boy\'s name?',
    'favourite girl\'s name?',
    'favourite celebrity?',
    'favourite hobby?',
    'favourite way to cheer you up?',
    'favourite hobby?',
    'favourite kind of gift to receive?',
    'favourite crafty thing to make?',
    'favourite way to relax?',
    'favourite musical',
    'recommended way to solve a dispute',
    'solution to climate change'
]